### ISSUE TITLE
Problem checking out git repository on windows

### ISSUE THREAD

**Issue by nfreire** [europeana/metis-framework#23]
There is a file with ':' in its name. When checking out the metis-framework repository from github on a windows machine, the checkout process fails.

Could the file be renamed?

It is this one:
https://github.com/europeana/metis-framework/blob/develop/metis-enrichment/enrichment-framework-knowledgebase/src/test/resources/http:/dbpedia.org/page/Georgette_Chen.xml

**Comment by ymamakis** [comment]
Yes I removed it..
does it still happen?

**Comment by nfreire** [comment]
Worked fine now.
Thanks!
